name: kNN
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - bleach=3.2.3=pyhd3eb1b0_0
  - ca-certificates=2021.1.19=hecd8cb5_0
  - certifi=2020.12.5=py38hecd8cb5_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=h18a8e69_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.10=hb1e8313_2
  - freetype=2.10.4=ha233b18_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.66.1=h9bbe63b_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.19.0=py38h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.18.0=py38hecd8cb5_1
  - jinja2=2.11.2=pyhd3eb1b0_0
  - joblib=1.0.0=pyhd8ed1ab_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.0=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.0=py38h23ab428_0
  - lcms2=2.11=h92f6f08_0
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=4.0.0=7_5_0_h1a10cd1_17
  - libgfortran4=7.5.0=h1a10cd1_17
  - libiconv=1.16=h1de35cc_0
  - liblapack=3.9.0=7_openblas
  - libllvm10=10.0.1=h009f743_3
  - libopenblas=0.3.12=openmp_h63d9170_1
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.1.0=hcb84e12_1
  - llvm-openmp=11.0.1=h7c73e74_0
  - llvmlite=0.34.0=py38h739e7dc_4
  - lz4-c=1.9.3=h23ab428_0
  - markupsafe=1.1.1=py38h1de35cc_1
  - matplotlib=3.3.2=hecd8cb5_0
  - matplotlib-base=3.3.2=py38h181983e_0
  - mistune=0.8.4=py38h1de35cc_1001
  - nbclient=0.5.1=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - notebook=5.7.10=py38_0
  - numba=0.51.2=py38h6440ff4_1
  - numpy=1.19.5=py38h6ced74f_1
  - olefile=0.46=py_0
  - openssl=1.1.1i=h9ed2024_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandas=1.2.1=py38hb2f4e1b_0
  - pandoc=2.11=h0dc7051_0
  - pandocfilters=1.4.3=py38hecd8cb5_1
  - parso=0.8.1=pyhd3eb1b0_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py38h5270095_0
  - pip=20.3.3=py38hecd8cb5_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.7.4=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.17.3=py38haf1e3a3_0
  - python=3.8.5=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.5=pyhd3eb1b0_0
  - pyzmq=20.0.0=py38h23ab428_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - scikit-learn=0.22.1=py38h3dc85bc_1
  - scipy=1.4.1=py38h38b60c6_3
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38hecd8cb5_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.15.0=py38hecd8cb5_0
  - sqlite=3.33.0=hffcf06c_0
  - terminado=0.9.2=py38hecd8cb5_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py38h9ed2024_0
  - traitlets=5.0.5=py_0
  - tslearn=0.5.0.5=py38hc7193ba_0
  - tzdata=2020f=h52ac0ba_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.3=hb1e8313_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - annoy==1.17.0
prefix: /opt/anaconda3/envs/kNN
